defaultHook:
  type: merkleTreeHook
defaultIsm:
  relayer: "0x4f0b4c4c23e31f3e5bcceffb649afde964b7df50"
  type: trustedRelayerIsm
owner: "0x4f0b4c4c23e31f3e5bcceffb649afde964b7df50"
proxyAdmin:
  owner: "0x4f0b4c4c23e31f3e5bcceffb649afde964b7df50"
requiredHook:
  beneficiary: "0x4f0b4c4c23E31f3e5bCCEfFb649AfdE964B7dF50"
  maxProtocolFee: "100000000000000000"
  owner: "0x4f0b4c4c23E31f3e5bCCEfFb649AfdE964B7dF50"
  protocolFee: "0"
  type: protocolFee

